#!/bin/bash
FIRST=$1
SIGN=$2
SECOND=$3
if SIGN=='+';
        then
        ADD=$(($1+$3))
        echo $ADD
elif SIGN='-';
        SUB=$(($1-$3))
        echo $SUB
elif SIGN='*';
        MUL=$(($1*$3))
        echo $MUL
elif SIGN='\';
        DEL=$(($1/$3));
        echo $DEL
fi
